# Generated by Django 6.0.5 on 2026-05-16 13:22

import apps.cart.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('menu', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.CharField(default=apps.cart.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(db_column='account_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cart', to='authentication.accounts')),
            ],
            options={
                'verbose_name': 'Shopping Cart',
                'verbose_name_plural': 'Shopping Carts',
                'db_table': 'carts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.CharField(default=apps.cart.models.generate_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity must be greater than 0', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price_snapshot', models.PositiveIntegerField(help_text='Price in pennies at time of addition (snapshot)')),
                ('line_total', models.PositiveIntegerField(help_text='quantity * unit_price_snapshot (in pennies)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(db_column='cart_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='cart.cart')),
                ('menu_item', models.ForeignKey(db_column='menu_item_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cart_items', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'db_table': 'cart_items',
                'ordering': ['created_at'],
            },
        ),
    ]
