# Generated by Django 6.0.5 on 2026-05-16 09:45

import apps.cart.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "cart_id",
                    models.CharField(
                        default=apps.cart.models.generate_uuid,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_id",
                    models.CharField(
                        db_index=True,
                        help_text="Foreign key to customer_accounts.account_id",
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ABANDONED", "Abandoned"),
                            ("CONVERTED", "Converted to Order"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shopping Cart",
                "verbose_name_plural": "Shopping Carts",
                "db_table": "carts",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "cart_item_id",
                    models.CharField(
                        default=apps.cart.models.generate_uuid,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "menu_item_id",
                    models.CharField(
                        db_index=True,
                        help_text="Foreign key to menu_items.menu_item_id",
                        max_length=36,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Quantity must be greater than 0",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "unit_price_snapshot",
                    models.PositiveIntegerField(
                        help_text="Price in pennies at time of addition (snapshot)"
                    ),
                ),
                (
                    "line_total",
                    models.PositiveIntegerField(
                        help_text="quantity * unit_price_snapshot (in pennies)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        db_column="cart_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cart.cart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
                "db_table": "cart_items",
                "ordering": ["created_at"],
                "unique_together": {("cart", "menu_item_id")},
            },
        ),
    ]
