# Generated by Django 6.0.5 on 2026-05-17 00:00

import apps.payments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "payment_id",
                    models.TextField(
                        blank=True,
                        default=apps.payments.models._uuid_str,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payment_method", models.TextField()),
                ("payment_status", models.TextField()),
                ("amount", models.IntegerField()),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="order.orders",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "transaction_id",
                    models.TextField(
                        blank=True,
                        default=apps.payments.models._uuid_str,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gateway_reference", models.TextField(blank=True, null=True)),
                ("authorization_code", models.TextField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
            },
        ),
    ]
