# Generated by Django 6.0.5 on 2026-05-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="attempt_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payment",
            name="checkout_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="client_secret",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="usd", max_length=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="gateway_reference",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="idempotency_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_intent_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
