# Generated by Django 6.0.5 on 2026-05-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accounts",
            fields=[
                (
                    "account_id",
                    models.TextField(blank=True, primary_key=True, serialize=False),
                ),
                ("display_name", models.TextField()),
                ("email", models.TextField(unique=True)),
                ("role", models.TextField()),
                ("password_hash", models.TextField()),
                ("phone_number", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "accounts",
                "managed": False,
            },
        ),
    ]
