# Generated by Django 6.0.5 on 2026-05-17 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'managed': True},
        ),
    ]
