# Generated by Django 6.0.5 on 2026-05-17 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_accounts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'managed': False},
        ),
    ]
