# Generated by Django 6.0.5 on 2026-05-17 02:46

import apps.order.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.TextField(blank=True, default=apps.order.models._uuid_str, primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField()),
                ('placed_at', models.DateTimeField()),
                ('order_status', models.TextField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.accounts')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('order_item_id', models.TextField(blank=True, default=apps.order.models._uuid_str, primary_key=True, serialize=False)),
                ('item_name_snapshot', models.TextField()),
                ('item_description_snapshot', models.TextField(blank=True, null=True)),
                ('unit_price_snapshot', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('line_total', models.IntegerField(default=0)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.orders')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('history_id', models.TextField(blank=True, default=apps.order.models._uuid_str, primary_key=True, serialize=False)),
                ('order_status', models.TextField()),
                ('note', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.orders')),
            ],
            options={
                'db_table': 'order_status_history',
            },
        ),
    ]
